---
- name: AI Models
  hosts: all
  become: true
  tasks:
    - name: Mars client
      ansible.builtin.include_role:
        name: ewc-ansible-role-mars-client-1.0

    - name: Ai-models
      ansible.builtin.include_role:
        name: ewc-ansible-role-ai-models-1.0
